### ISSUE TITLE
fix(invites): add default timeout for invites

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#129]
## Description

Currently invites do not have a default timeout, but the docs say they should. 1 minute? 5 minutes?

**Comment by EvanHahn** [comment]
It looks like this was addressed for the invitor in b95bfbfcac7bc9ad68181cfa4b86047c46c8fb4a. I don't think invitees need a timeout.

I'm going to close this issue but let me know if that's wrong!
