### ISSUE TITLE
Add `$member` namespace method to project instance API

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#133]
- `$member.invite()`
- `$member.update()` - descope for MVP
- `$member.remove()` - descope for MVP
- `$member.getById(deviceId)`
- `$member.getMany()`

- Events
    -`member-update`

Needs to contain deviceId and name, which are stored in the (auth) hypercores, and needs to also include information from connections (which devices/members are connected) and also sync state (eg wants vs haves vs shared).

**Comment by achou11** [comment]
TODO for me: break this up into smaller tickets and close this

**Comment by achou11** [comment]
Closing this issue as:

- `member.invite()` has been implemented via https://github.com/digidem/mapeo-core-next/issues/225
- the other methods have specific issues dedicated to each of them (see #255, #256, #257, and #258)
