### ISSUE TITLE
add types for dependencies

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#14]
In particular:

- [ ] `brittle`
- [x] `multi-core-indexer`
- [x] `@mapeo/sqlite-indexer`
- [x] `@mapeo/crypto`
- [ ] `sodium-universal`
- [ ] `base32.js`

and anything else in https://github.com/digidem/mapeo-core-next/blob/main/types/modules.d.ts

**Comment by achou11** [comment]
a good reference in case i start losing steam...

https://github.com/digidem/multi-core-indexer/tree/main/types

**Comment by achou11** [comment]
note to self, `base32.js` already has ts defs but they're not published with the module right now (currently available on master branch)

**Comment by sethvincent** [comment]
updated the list to reflect newly added types 🎉

**Comment by achou11** [comment]
relevant thing that Gregor started work on: https://github.com/digidem/digidem-types

**Comment by gmaclennan** [comment]
done, enough for now
