### ISSUE TITLE
Add device info records

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#182]
## Description

The purpose of a device info record is to store metadata about a particular device. Currently this is a human-friendly name. In the future we might want to add additional metadata based on user requirements.

The device info records should be stored in the 'config' namespace so that they are not readable by someone who has only the auth namespace encryption key, but so that they are synchronized before sync of data and blobs, which allows us to display a device name in the UI before a user decides to sync.

<ins>Who can write device info records (e.g. who can name a device)?</ins>

This hasn't been fully discussed with the co-design team, but initially I think it makes sense to only allow the device owner to write a device info record. We might want to in the future only allow admins to write device info records for devices in a project, or treat a device info record written just by the device itself as "unverified" and a record written by an admin as "verified". For the MVP let's not check / control who can write this, in the app we'll only allow the device itself to write this record.

The schema type is simple:

```ts
type DeviceInfo = {
  name: string,
}
```

The `docId` should be the identity public key (which we are using as the device ID).

In the future we can lookup where a device info record comes from:

```js
const { coreKey } = parseVersionId(deviceInfo.versionId)
const deviceKey = coreOwnership.getOwnerKey(coreKey)
if (deviceKey.toString('hex') === deviceInfo.docId) {
  // record is written by "self" e.g. device has written its own device info
} else {
  // look up role from deviceKey and decide what to do with the record based on that info.
}
```

## Tasks

- [x] digidem/mapeo-schema#126
- [x] #190 
- [x] #249

**Comment by achou11** [comment]
lgtm!

> This hasn't been fully discussed with the co-design team, but initially I think it makes sense to only allow the device owner to write a device info record. We might want to in the future only allow admins to write device info records for devices in a project, or treat a device info record written just by the device itself as "unverified" and a record written by an admin as "verified". For the MVP let's not check / control who can write this, in the app we'll only allow the device itself to write this record.

I agree with this 👍

**Comment by gmaclennan** [comment]
Completed in #250
