### ISSUE TITLE
create directory & readme file for discovery.js module

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#19]
i think we're going to follow a pattern of each big module in the lib folder living in a directory with a README.md file, so we can start doing that with discovery.js

tasks:
- move lib/discovery.js to lib/discovery/index.js
- decide what these internal readme files should include (basic description, usage example, link to tests, what else?)
- create README.md file with content

**Comment by sethvincent** [comment]
@achou11 here's what I've got so far for other module readmes in the lib directory: https://github.com/digidem/mapeo-core-next/pull/16/commits/a1be680f98fd4283eaa82060c6bda28df46b93a4

Anything else we should have in there?

**Comment by achou11** [comment]
> @achou11 here's what I've got so far for other module readmes in the lib directory: [a1be680](https://github.com/digidem/mapeo-core-next/commit/a1be680f98fd4283eaa82060c6bda28df46b93a4)
> 
> Anything else we should have in there?

can't think of anything else beyond what you listed :)
