### ISSUE TITLE
Create class that implements `invite` namespace API

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#198]
## Description

We need to implement the client-level API specified in https://github.com/digidem/mapeo-core-docs/blob/main/client-docs/README.md#clientinvite. We currently have a `MapeoRPC` class that manages _sent_ invites but we need something that will handle _incoming_ invites and account for multiproject (note, not necessarily multi-peer). Instead of updating that implementation, we should implement another class that uses an rpc instance and is responsible for handling incoming invites and responding to them based on project. 

Some pseudocode for an imagined implementation:

```ts
// Create the class that manages these invites
class InviteApi {
  // Accepts a MapeoRPC instance
  constructor({ rpc })
    this.rpc = rpc

    // attach listener for 'invite' event, re-emit as 'invite-received'
    // Track project key, and encryption keys for invite.
    // dedupe - if we receive two invites for same project, 
    // *do* track the clientId that need to respond to, but *don't* emit twice
  }

  accept(projectId) {
    const clientIds = this.#getClientsThatSentInvite(projectId)
    for (const clientId of clientIds) {
        this.rpc.inviteResponse(clientId, { projectId, decision: 'ACCEPT' })
      }
    }

  reject(projectId) {
    // similar to above
  }
}
```

Based on initial discussion, minimal changes are needed in the `MapeoRPC` class implementation, which are being tracked in https://github.com/digidem/mapeo-core-next/issues/197 and #196 

## Tasks

- [ ] implement `InviteApi` class

**Comment by gmaclennan** [comment]
Let's call it `InviteApi` to match that we call the class for `$blob` `BlobApi`.

**Comment by achou11** [comment]
> Seems like this should be a separate issue.

@sethvincent good point. created a separate issue here: https://github.com/digidem/mapeo-core-next/issues/212
