### ISSUE TITLE
manager.getProject(projectId) fails

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#236]
## Description

Trying to call `manager.getProject(projectId)` on a project that has been added or created fails.

This is due to a bug in the encoding of project keys

We should have tests for this. A fix is in https://github.com/digidem/mapeo-core-next/pull/235/commits/5a2f8a12ff48b10321a355480dc8af2ed08d0892

**Comment by achou11** [comment]
Fix in #226. Test updates in #237
