### ISSUE TITLE
Expose "ownCapabilities"

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#239]
## Description

We need a way to get a device's own capabilities. This will be used to show the correct UX depending on what a device's capabilities are (e.g. if a device is able to assign roles, then it is able to invite other devices).

Not sure what the best API for this is? `project.getOwnCapabilities()`?

**Comment by achou11** [comment]
would it make sense to incorporate this as part of `project.$getProjectSettings`? maybe the separation is better, but just a thought

**Comment by gmaclennan** [comment]
To me at least, project settings implies they are settings that apply across the project, that can be set via `setProjectSettings`. It's not possible for a user to set their capabilities, and capabilities are a device-specific setting, not a project setting. We could expose this via the `member` API. I imagine that for a screen that shows a list of project members, you would want to at least see the role name ('Coordinator', "Member" or "Blocked"), but it could be handy to be able to drill-down and get the capabilities of each device.

I suggest that `$member.getById()` returns a property `capabilities`, with the object that defines the capabilities. So a device would call `project.$member.getById(ownDeviceId)`
