### ISSUE TITLE
Question: How to expose setting device name in the API?

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#240]
## Description

We need a public method for setting a device name. In the future we might want to set additional metadata in addition to the name. Initially a device will only be able to set its own name, but in the future we might want to enable setting of other devices names (e.g. a project coordinator might want to choose the names of other devices).

Suggestions:

- `project.$setDeviceInfo()`, `project.$getDeviceInfo()`

**Comment by achou11** [comment]
is this different than what the `$member` namespace provides?

https://github.com/digidem/mapeo-core-docs/blob/main/client-docs/README.md#projectmember

**Comment by gmaclennan** [comment]
Good question, perhaps that API is sufficient? Actually just realizing that we also need to set device name at a device-level (e.g. across projects), and this would be the default for any projects that you join.

**Comment by achou11** [comment]
> Good question, perhaps that API is sufficient?

I think it should be for what you're originally describing

> Actually just realizing that we also need to set device name at a device-level (e.g. across projects), and this would be the default for any projects that you join.

yeah I think it makes more sense for this issue to suggest a client-level api e.g. `client.setDeviceInfo`

**Comment by achou11** [comment]
closed via #249
