### ISSUE TITLE
send device info on first RPC channel connection

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#316]
## Description

Extracted from #245 

This requires work in the mdns implementation, whose connection events are used to determine when to create the rpc channel connection with the peer

## Tasks

- [ ] Update mdns implementation to create rpc channel when a desired connection is made
- [ ] send device info when rpc channel is created

**Comment by EvanHahn** [comment]
Is this already done [here](https://github.com/digidem/mapeo-core-next/blob/30e637ba74168d106e17d7b3de349abd97f51c74/src/mapeo-manager.js#L270-L273)?

**Comment by gmaclennan** [comment]
yes, done.
