### ISSUE TITLE
Expose an API method to get own deviceId

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#372]
## Description

The client needs a way to access the devices own deviceId, and also a way to look up own capabilities. This can be used to device what actions (edit/delete/create) can be done on different record types.

Two possible API options:

1. Include it in `manager.getDeviceInfo()` - this makes sense for deviceId, but not necessarily for capability information, which is project-specific.
2. Add a `project.member.getOwn()` method that returns the same `MemberInfo` type that `project.member.getById()` returns, e.g. device name, device ID, and capabilities.

I think maybe it makes sense to do both - they both should be easy one-line changes.

**Comment by achou11** [comment]
don't we already expose the device id in the MapeoProject?

https://github.com/digidem/mapeo-core-next/blob/main/src/mapeo-project.js#L94

**Comment by gmaclennan** [comment]
True, I had forgotten about that - I had mainly put that there for tests. However I think it still makes sense to expose it via `manager.getDeviceInfo()` and `project.member.getOwn()` because you will often want it alongside `capabilities` and `deviceName`.

**Comment by gmaclennan** [comment]
True, however remember that properties must be accessed as async functions over IPC, so it would be `await project.$member.getById(await project.deviceId())`, so `member.getOwn()` is really a convenience function to avoid needing to write that (also a small performance improvement)

**Comment by EvanHahn** [comment]
`manager.getDeviceInfo()` started returning `deviceId` in f20c832fbf6feaf4a78224436aacf60a3bbc1c3a. Maybe that's sufficient?

**Comment by achou11** [comment]
@EvanHahn yeah I think we can close. not sure if the need for (2) has come up yet, but if we think it's useful, maybe create separate issue?
