### ISSUE TITLE
type checking in `tests/` directory doesn't use tsconfig (fully?)

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#416]
Working on a new file in `tests/` and noticed that our vendored digidem types definitions aren't being detected in it. Most of the files in that directory don't have typechecking enabled and the ones that do are done via `// @ts-check` in order to gradually integrate typechecking in that directory. However, with the `// @ts-check`, it seems like TS is just inferring types based on reading the source module as opposed to using the tsconfig to resolve some of the external module types, which works in some cases but overall doesn't work given the complexity of some of the hypercore-related types.

if you do `npx tsc --showConfig`, you'll notice that - with the exception of one file, `tests/schema.js` (which is explicitly listed in the `files` tsconfig field) - none of the `tests/` files with the `// @ts-check` annotation are listed in the `files` field i.e. having the tsconfig being applied to it. This leads me to believe that using `// @ts-check` doesn't (fully) apply the closest found `tsconfig.json` file as I expected. I find it hard to believe that TS will just apply its default configuration in this case, so maybe it does something clever that isn't transparent to me. 

The solution would be to update the tsconfig to either

- add each file in the `files` field (granular, but tedious)
- adding the `tests/**/*` in the `include` field (less tedious but then we have to deal with all of the type errors that haven't been addressed)

Was able to confirm that vendored type resolution is fixed applying either of the above options.

**Comment by gmaclennan** [comment]
I think we can add a `tsconfig.json` to the `tests/` folder, and extend the main tsconfig in that, plus include the test files. This avoids including test files in the type tests and emitting types, but still allows the editor to check them.
