### ISSUE TITLE
fix: `dataType.delete()` should use `docId` not `versionId`

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#422]
## Description

Reading through #420 made me realize that I think our current `delete()` method does not make sense. Trying to "delete" an arbitrary version of a doc doesn't actually do anything unless it is a "head". It will actually create a fork, which is kind of confusing.

e.g. we have a doc with docId `X`, created with versionId `A`. It is then edited so we have version `B`. Now a user tries to delete version `A`. They will create a new version `C`, and we now have two "heads" or "forks": `B` and `C`.

I think the delete method should actually accept the `docId`, since what you actually expect from deletion is that the document is no longer returned from `getMany()`. The delete function should:

1. Get the existing doc for that `docId`, and get the versionId
2. Check the `forks` property, and also get the existing doc(s) for those forks, to get the versionIds
3. Create a doc with `deleted: true` that has `links` with the versionIds above.
4. For the document data that is written to the delete doc, use the value from (1) (e.g. the doc that would be returned from `dataType.getByDocId(docId)`.

@achou11 @tomasciccola thoughts or comments?

**Comment by gmaclennan** [comment]
This could raise the question, "how do I delete a fork", which you do as:

```js
const obs = await project.observation.getByDocId(docId)
const merged = await project.observation.update([obs.versionId, ...obs.forks], valueOf(obs))
```

Could look at creating a helper for this in the API if needed once we introduce a UI for managing forks.

**Comment by achou11** [comment]
yeah i think this makes sense. So basically:

- `DataType.delete()` is reserved for deleting the latest locally known version of a record
- if needed, you could technically use `DataType.update()` to delete an older version or delete a fork?

**Comment by gmaclennan** [comment]
yeah, although "deleting an older version" and "deleting a fork" doesn't really have a clear meaning.
