### ISSUE TITLE
RFC: translation of runtime strings

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#456]
## Description

Most of translation is of static strings, e.g. strings that are defined in the frontend app codebase. However some strings related to project configuration are defined at runtime, and we need a way to translate these. Examples include:

1. Presets and fields: Each preset has a name, and fields for a preset have a label (e.g. question presented to the user) and an optional placeholder. The default presets and fields that we ship are multi-lingual, and there are partner use-cases for creating custom presets and fields that are multi-lingual, if the same presets are to be used with different linguistic groups.
2. Role names and descriptions - we are hard coding role definitions currently (we call them "capabilities" at the moment), but we are allowing the possibility of custom roles in the future. If these names are stored in the database then we should also store the translations in the database.
3. Place names - once we add mapping capabilities, nodes and ways might have tags (like "placename") which have translations, e.g. Spanish name and local indigenous name.

Essentially, we need a way to add translations to properties of records stored in the mapeo core database.

### Possible approaches

1. Add additional fields / tags. This is how OpenStreetMap does it - there is a `name` tag, and then a `name:es` tag for the Spanish language name.
2. Create a separate `translation` record type, that maps a stringId + languageCode to a translated string.

We could combine both these approaches - it might make sense to maintain OSM compatibility for tags (which do not follow a schema in the backend - they are essentially untyped), but for other record fields which are strictly typed, we could use approach (2). The advantage of (2) is that adding translations does not require editing records, which is costly given the immutable nature of the database.

One idea for implementing (2):

- One `translation` record for each string translated into each language.
- Deterministic `stringId` which can be `{recordId}.{fieldId}[{languageCode}` where `fieldId` is a reference to a record field in dot-prop notation and `languageCode` could be BCP-47 or ISO 638-3, but ideally something where we could easily lookup the fallback for say `en-GB` in `en-US`., e.g. the Spanish translation of the string "hello" on a record `{ type: 'observation', { foo: { bar: 'hello' } } }` would have the `stringId` of `observation.foo.bar[es]`.
- `message` would be the translated string

We could define this as a dataType and our existing indexes would put all of these in a sqlite table.

### How to read translated strings via the API

A few of initial ideas:

1. Add a `language` option to API read methods, which would lookup translations and replace strings e.g. `project.preset.getMany({ language: 'es' })`
2. Append translations to records returned by API read methods
3. Expose all translations to the frontend as `project.translation.getById()` and leave translation entirely to the frontend.

One downside of (3) is the extra round-trips to the backend, and needing to handle the "untranslated" state while waiting for the translation to be returned (since all interaction with the backend is async).

**Comment by tomasciccola** [comment]
I think I have a clearer understanding with option 2 (option 1 seems more versatile since tags are untyped but also less clearer path). But at the same time I don't have it super clear.
Given what you propose, I imagine a translation record like so:
```protobuf
message Translation {
  type: string // lets say, 'field' or 'role', maybe unnecessary?
  recordId: byte[] // the id that points to the record we want to get a translation for
  fieldId: string // the field from that record that we want to translate the string for
  languageCode: string // BCP-47 or ISO 638-3
  value: string // the actual translated string??
 
}
```

but maybe I'm way off?

**Comment by gmaclennan** [comment]
Yes, I think that's pretty close - actually further along than what I had been thinking. A couple of suggestions:

- I think maybe keep `type` (maybe change the name to `recordType`?), since there are not actual guarantees that `recordId` is globally unique (it is unique within a record type).
- Rather than `fieldName: string` use `fieldRef: string[]`, so that the string`hello` in `{ foo: { bar: 'hello' } }` would have a `fieldRef: ['foo', 'bar']`
- For `value`, I think we call this `message` in translation docs, so maybe we can keep to that.

For implementation, I think we can use our existing `DataType` class to implement this, but we should create the records with a custom `docId` (rather than the random one we currently use), which should be a hash of `recordType`, `recordId`, `fieldRef`, `languageCode`. This will make the indexer treat changes to `message` when the other values stay the same as edits. We would also need to patch the `update` method of the `dataType` class to ensure that these fields are not modified.

For tag translations, e.g. a translation of a tag on an observation, I wonder whether we just store them as additional tags e.g. `name:es`, rather than use these translation records, because I think the use-case is different - when viewing this data a user would generally want to see all translations, where-as when viewing a preset or field, a user would only want to see the translation of messages into the UI language.

**Comment by gmaclennan** [comment]
Yeah I think that sums it up. However rather than updating DataType I think maybe we can add a simple `$translation` API that wraps the dataType instance, then rather than getByDocId we have `$translation.get({ langcode, fieldRef, etc })`

I'm thinking tag translation can be an entirely front end thing - no need for the backend to know about it. My concern with doing it this way is that it would add complexity for the front end code to request all the translations for each field displayed.

**Comment by EvanHahn** [comment]
Closing because this RFC has been resolved. See #515 for an implementation.
