### ISSUE TITLE
Fire event when peer's name changed during local discovery

### ISSUE THREAD

**Issue by EvanHahn** [digidem/mapeo-core-next#497]

**Comment by EvanHahn** [comment]
@ErikSin It looks like we already fire the `peers` event when someone's name changes, so this might already be done...

Does that work for you?

**Comment by ErikSin** [comment]
> @ErikSin It looks like we already fire the `peers` event when someone's name changes, so this might already be done...
> 
> Does that work for you?

It's currently not emitting a name when the name changes. And according to Gregor, that was never in the design/code

**Comment by EvanHahn** [comment]
We have [a few tests][0] that assert that the `peers` event is emitted when the device info changes, which includes the name. It [looks like][1] that's how the device name is changed on the frontend, so I would expect this to already be working. (It looks like that was added in `@mapeo/core@9.0.0-alpha.1`, so it's not like it's only on an unreleased version of `@mapeo/core`...)

Maybe there's a bug somewhere, or something obvious I'm not understanding...any thoughts?

[0]: https://github.com/digidem/mapeo-core-next/blob/c402e484738e3fd6832388d06a6ab6b61c7c8a73/tests/local-peers.js#L606-L679
[1]: https://github.com/digidem/CoMapeo-mobile/blob/5f6b225857a1c065456cee72c55888cf53ac0d70/src/frontend/hooks/server/deviceInfo.ts#L22

**Comment by EvanHahn** [comment]
See #502 for more details.

**Comment by EvanHahn** [comment]
I was wrong. It looks like this issue is already done (firing an event when a peer's name changes) but #502 is not (informing peers of your own name change).

Closing this issue and re-opening #502.
