### ISSUE TITLE
Get list of keys in a corestore namespace

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#53]
## Description
Since corestore doesn't have a mechanism to get every core in a namespace, the idea is to store a sql table with `type,coreId,identityId` where `type` can be something like `auth|data|blob` so that we can get all the coreIds given a type

## Tasks
- [x] Create a coreIdCache class that allows you to store a row of `type,coreId,identityId` and allows you to get every coreId of a `type` or `identityId`

**Comment by tomasciccola** [comment]
regarding [this](https://github.com/digidem/mapeo-core-next/issues/49#issuecomment-1346904991) comment, maybe `coreId` should be a foreign key that maps to `version` in Doc and when we do the query in coreIdCache we actually return the Doc where `coreId/{core.length}` matches `version`. Does this makes sense? (I'm not well versed in sql so not sure...)

**Comment by sethvincent** [comment]
Ah yeah the return types in lib/sqlite.js should be more general. 

The `CoreIdCache` class is looking good! Added a couple comments here: https://github.com/digidem/mapeo-core-next/commit/e2e9c1ea18cf34a48e94ace1ed888d4cd578f885

**Comment by tomasciccola** [comment]
regarding return types in lib/sqlite.js, I thought that making a union type like `{(Doc | CoreIdRecord)} SqliteDoc` would work if sqlite.query returns `SqliteDoc` but it didn't. In typescript I think this is solved using control flow and `var as Type` ...

**Comment by tomasciccola** [comment]
with the current implementation, if one does smth like `coreIdCache.put()` it will throw since in the table we constrain `namespace`  to a set of possible strings.
But if we do `coreIdCache.put({namespace:'auth'})` then the row will be put on the table without errors with the `coreId` and `identityId` as `'undefined'`. I thought that the `NOT NULL`restrain would check for it, but it doesn't. Should we add assertions on put? or should we leave it at that since jsdoc checking should be enough?

**Comment by gmaclennan** [comment]
I don't think we need to track/store `identityId` in the `coreIdCache`. The auth store should manage all of this: as I understand it we have an "ownership" record type in the auth store, we should generate a materialized view of this which is the core key <--> identity key link. This class I think should only worry about:

1. Public keys of all cores in project
2. Which "namespace" they are part of

**Comment by gmaclennan** [comment]
Implemented in #61, with the sqlite table used only for persistence across restarts - read queries are all in-memory.

**Comment by gmaclennan** [comment]
Closing since this was done in #61
