### ISSUE TITLE
Publish & integrate custom module definitions

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#58]
We have written several custom module definitions (hypercore, random-access-storage etc) here, but we use them in a few different modules (e.g. [multi-core-indexer](https://github.com/digidem/multi-core-indexer)).

Ideally we publish these all to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), however that is time consuming and probably requires the types to be more complete.

For our internal use I think it would be useful to publish these types to an npm package for our own internal use. We could call this `@mapeo/external-types` and then include it in modules that use it (like this one) via the `"typeRoots": ["./node_modules/@mapeo/external-types"]` in `tsconfig.json`.

Note that the behaviour is slightly different from how `./node_modules/@types` works: `typeRoots` will not be used in module resolution to look up types, only for including types in the global scope, so we need to continue to wrap all our declarations in `declare module "module-name"` (which is not necessary for types published to `@types`).

Proposal summary: extract module definitions from `./types` in this repo and move them into a separate npm module `@mapeo/external-types`, as a temporary measure until we feel ready to either publish to DefinitelyTyped, or contribute types to upstream modules.

@achou11

**Comment by achou11** [comment]
related to https://github.com/digidem/digidem-types?

**Comment by gmaclennan** [comment]
Closed via #125
