### ISSUE TITLE
Block non-local connections on mdns server

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#68]
We [create a tcp server](https://github.com/digidem/mapeo-core-next/blob/f296696881863d74cc23aca0cf694840038edb5b/lib/discovery/index.js#L73) for listening to mdns connections, but theoretically this could receive connections from outside the local network.
We should reject/block incoming connections from non-local addresses. We can maybe do this by checking [`socket.remoteAddress`](https://nodejs.org/api/net.html#net_socket_remoteaddress) against private IP ranges with something like https://github.com/mafintosh/bogon
The reason for doing this is a security precaution, particularly if we are sending invites to peers discovered through mdns, and we want to be sure that incoming connections are local network only.

**Comment by tomasciccola** [comment]
I was wondering how can we test this. Should we have a publicly accessible node that does mdns and connects to a predefined topic, so we can reject it on a test?

**Comment by gmaclennan** [comment]
This should be fixed in the latest implementation
