### ISSUE TITLE
User cannot leave project as the only device

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-core-next#717]
Currently if a user tries to leave a project using `mapeoApi.leaveProject(projectId)`, and they are the only user on that project, they are unable to leave a project. The Error `Cannot leave a project as the only device` is thrown.

This is undesired behaviour for a few reasons:
1. We do not warn the user that they are unable to leave a project when they create a project.
2. Difficult for QA testing. Qa tester's usually only have 2 devices. It they want to test the different states of being invited to a project while on a project, they will be blocked.
3. This discourages the user from testing out the creation of a project as they will be trapped in that project unless they invite someone else.

**Comment by EvanHahn** [comment]
I'll take this on.
