### ISSUE TITLE
Validate config file version when importing

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#718]
## Description

We could update the version of the config file in the future in a way that would break compatibility. This would result in preset import from older clients from the new config file format failing in unexpected ways.

I think it's important for MVP to validate a file version when reading a config file. We also need to write this version to the file when we generate it. Config import should fail with a recognizable error if the user tries to import a config file that is newer than what the client is able to import.

We could just use an integer for the config file version and increment it for any change that would cause an older client to not be able to import it.

We could alternatively have a `{MAJOR}.{MINOR}` file version, with minor changes being additions to the format that are ignored by older clients without errors. In this case the version validation can not throw an error for larger minor versions, but it could display a warning.

## Tasks

- [ ] Update the config file generation code to write a file version to the zip archive
- [ ] Update the config import code to check the file version is known before trying to import it, and throw an error if not.

**Comment by tomasciccola** [comment]
this was done when https://github.com/digidem/mapeo-core-next/pull/721 was merged
