### ISSUE TITLE
incorrect sync state when data collected for a project happens before new device is added to project

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#724]
Reproduction steps:

1. Device A creates project
2. Device A creates observation
3. Device A adds Device B to project
4. Device B detects syncable changes and enables sync. Device A **does not detect syncable changes**

Looking at the sync state for Device A in step (4), this is the value of `data` in the sync state:

```json
{"dataToSync": false, "have": 1, "isSyncEnabled": false, "missing": 0, "want": 0, "wanted": 0}
```

I would've expected `wanted` to be `1` and thus `dataToSync` to be `true`

If Device A or B create another piece of data (e.g. observation) after step (4), then that bypasses the issue and both devices are able to detect syncable changes. Did not confirm if the sync state `data` payload is actually accurate in that case on Device A though.

**Comment by EvanHahn** [comment]
I wrote a test to try to reproduce this, and could not (i.e., the test passes):

```javascript
// In test-e2e/sync.js
test.only('tells newly-invited managers about existing data', async (t) => {
  const managers = await createManagers(2, t)
  const [invitor, ...invitees] = managers
  const [invitee] = invitees

  // 1. Device A creates project

  const projectId = await invitor.createProject({ name: 'Mapeo' })
  const invitorProject = await invitor.getProject(projectId)
  t.after(() => invitorProject.close())

  // 2. Device A creates observation

  await invitorProject.observation.create(valueOf(generate('observation')[0]))

  // 3. Device A adds Device B to project

  const disconnectPeers = connectPeers(managers, { discovery: false })
  t.after(disconnectPeers)
  await invite({ invitor, invitees, projectId })

  const inviteeProject = await invitee.getProject(projectId)

  // 4. Device B detects syncable changes and enables sync. Device A does not detect syncable changes

  console.log('invitor state', invitorProject.$sync.getState().data)
  // { have: 1, want: 0, wanted: 1, missing: 0, dataToSync: true, isSyncEnabled: false }
  console.log('invitee state', inviteeProject.$sync.getState().data)
  // { have: 0, want: 1, wanted: 0, missing: 0, dataToSync: true, isSyncEnabled: false }

  assertDataSyncStateMatches(
    invitorProject,
    { have: 1, wanted: 1, dataToSync: true },
    'Invitor project should have something to sync'
  )
  assertDataSyncStateMatches(
    inviteeProject,
    { have: 0, want: 1, dataToSync: true },
    'Invitee project should learn about something to sync'
  )

  inviteeProject.$sync.start()
  await delay(1000) // Seems unnecessary, but added just in case

  assertDataSyncStateMatches(
    invitorProject,
    { have: 1, wanted: 1, dataToSync: true },
    'Invitor project should have something to sync'
  )
  assertDataSyncStateMatches(
    inviteeProject,
    { have: 0, want: 1, dataToSync: true },
    'Invitee project should learn about something to sync'
  )
})
```

I'll keep digging.

**Comment by EvanHahn** [comment]
I don't have a fix yet, but I can now reproduce the problem.

Calling `invitorProject.$sync.getState()` caches a result that isn't updated when a new peer connects. Removing the cache solves this problem, but creates other issues which I don't yet understand. I'll hopefully have a solution soon.

**Comment by EvanHahn** [comment]
This seems to be the issue:

1. Device A creates a project.
1. Device A creates an observation.
1. Device A reads the sync state.
1. Device A invites Device B.
1. Device A reads the sync state again. _It's wrong!_ It's the same state as in Step 3.

Here's a failing test:

```javascript
test('updates sync state when peers are added', async (t) => {
  const managers = await createManagers(2, t)
  const [invitor, ...invitees] = managers

  const projectId = await invitor.createProject({ name: 'Mapeo' })
  const invitorProject = await invitor.getProject(projectId)
  t.after(() => invitorProject.close())

  await invitorProject.observation.create(valueOf(generate('observation')[0]))

  assertDataSyncStateMatches(
    invitorProject,
    { have: 1, wanted: 0, dataToSync: false },
    'data sync state is correct at start'
  )

  const invitorProjectNoticesInvitee = pEvent(
    invitorProject.$sync,
    'sync-state',
    ({ data: { dataToSync } }) => dataToSync
  )

  const disconnectPeers = connectPeers(managers, { discovery: false })
  t.after(disconnectPeers)
  await invite({ invitor, invitees, projectId })

  assertDataSyncStateMatches(
    invitorProject,
    { have: 1, wanted: 1, dataToSync: true },
    'there should be something to sync'
  )

  await invitorProjectNoticesInvitee
})
```

This seems to be an issue with a stale cache, and I can fix it by [removing the cache](https://github.com/digidem/mapeo-core-next/compare/temporary-branch-2024-07-29-remove-sync-state-caches). (I don't intend to remove the cache permanently, but it's useful to test my theory.)

However, this causes [another test to fail](https://github.com/digidem/mapeo-core-next/blob/001f205d0883399b47ee964a1c0653b303188df2/test-e2e/sync.js#L440), one that ensures cores are shared properly.

After several hours, I cannot figure out why this is failing. The test seems to be set up correctly. The non-initial cores (`blob` and `data`) seem not to be shared for reasons I don't understand. Why does removing the caches cause this problem? Shouldn't the caches only be there for performance?

If anyone has ideas, I'm keen to hear them.

**Comment by EvanHahn** [comment]
Figured it out! Opening a PR shortly.
