### ISSUE TITLE
Expose number of syncing devices in Sync Api

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-core-next#742]
## Description

Currently the sync state returned by the sync API only includes `connectedPeers`. There is no way in the sync API to know the number of devices that are actually syncing with the current device.

## Tasks

- [ ] Add a new property to Sync State `syncingPeers`, which is the number of peers that the current device is syncing with.

See also #743 

See discussion : https://www.notion.so/digidem/QA-Sync-bug-Synced-progress-3-devices-3de5f1760e934b12b673bb49b62572ec

**Comment by EvanHahn** [comment]
We plan to address this with #743, so there's no need for this issue. Closing.
