### ISSUE TITLE
don't delete presets, fields and translations if the config-import fails

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#761]
Before importing a config, we delete all presets, fields and observations. But if the import fails, then you end up with nothing.
We should actually check that the config was successful  before deleting the older docs.

**Comment by tomasciccola** [comment]
I'm wondering about approaches to this. 
Since there are two steps to loading a config (reading it, and loading it into the db), there's two places where it can fail. If we want to make sure both are successful before deleting the old docs I think the best approach is:
1. Get all the _current_ config related docs (presets, fields, translations) (probably just their ids)
2. Load the config
3. Import it
4. If successful, use the stored ids to delete those previous documents

**Comment by EvanHahn** [comment]
I think that approach sounds good.

If someone adds data _during_ config import, those won't get deleted, but I think that's hard to avoid.

Let me know if you want to pair on this at all.
