### ISSUE TITLE
Finalize schemas

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#78]
We need to finalize the schemas for data types used in mapeo-core.

A partial list of schemas includes:

- Observation
- AuthStore
  - CoreOwnership
  - Device
  - Role
- ConfigStore
  - DeviceInfo
  - ProjectInfo
  - (additional schemas for all project config, including categories, fields, etc.)

Related issue in mapeo-schema: https://github.com/digidem/mapeo-schema/issues/25

**Comment by ximenabb** [comment]
@gmaclennan

**Comment by tomasciccola** [comment]
I think, in order to be done with schema design and be able to move on - and taking into account backwards compatibility - we should have a round of _***deep***_ schema revision. I can create an issue for that but mostly entails maybe meeting and going through schemas and check for possible issues/shortcomings
@gmaclennan @sethvincent wdyt?

**Comment by tomasciccola** [comment]
In [here](https://github.com/digidem/mapeo-schema/issues/25) there's the mention of BlobStore schemas not yet defined. I couldn't find any reference on the blobstore branch regarding schemas. Should we takle this now?

**Comment by tomasciccola** [comment]
> I think, in order to be done with schema design and be able to move on - and taking into account backwards compatibility - we should have a round of __**deep**__ schema revision. I can create an issue for that but mostly entails maybe meeting and going through schemas and check for possible issues/shortcomings @gmaclennan @sethvincent wdyt?

Going back to this, we should take the time to revise all the latests versions of schemas to see any nuances, missing or innecessary fields, better approaches, eetc..
Thinks I've noticed:
* required fields doesn't seem to be inherited:
i.e. `Common` JSONSchema has `created_at` as required but this doesn't seem to be checked on `Field_2` automatically; we need to also add `created_at` as required on `Field_2`
* `additionalProperties` doesn't seem to take "inherited" schemas. 
i.e. if `Field_2` inherits from common (by using `allOf: [{"$ref":"../common/v1.json"}]`) but has `additionalProperties` set to `false`, validation of the schema will fail when you add fields that are 'inherited' from `Common` (like `created_at`)
* Discrepancies when defining a field as a literal
i.e. `schemaType` is always a literal (it must be `Observation` for example). In some schemas this is denoted as `"pattern": "^Observation$"` and in others as `"enum":["Observation"]`. We should choose only one approach for new record versions

@gmaclennan @achou11 maybe we should take some time to revised this in the following weeks? Probably a meeting where we go through every schema is a good staring point...

**Comment by gmaclennan** [comment]
Split into smaller issues since this is a larger task:

- digidem/mapeo-schema#69
- digidem/mapeo-schema#70
- digidem/mapeo-schema#64 
- digidem/mapeo-schema#68
-
