### ISSUE TITLE
Potential replication state perf improvements

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#99]
> This has a (kinda optional) dependency on #100 so that we can track perf improvements

- https://github.com/digidem/mapeo-core-next/pull/60#discussion_r1129654874 Because this getter might be accessed frequently, maybe just copy-paste the isSynced() code into the loop/reducer above, to avoid iterating through the states twice.
- https://github.com/digidem/mapeo-core-next/pull/60#discussion_r1129659067 Not sure how often this is read, but if it is used frequently then consider maybe storing the peers Set on the class instance, and updating it within the coreState.on('state') handler
- https://github.com/digidem/mapeo-core-next/pull/60#discussion_r1129741244 I'm concerned about the perf of this. We are iterating the entire bitfield (which could be hundreds of records) for every block downloaded. Maybe consider partial updates like in https://github.com/digidem/hypercore-replication-progress/blob/main/index.js#L57-L74 ?

**Comment by gmaclennan** [comment]
Completed in new CoreSyncState
